pipeline {
  agent {
    kubernetes {
      yaml """
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
"""
    }
  }
  stages {
    stage('Build with Kaniko') {
      steps {
        container(name: 'kaniko', shell: '/busybox/sh') {
          
          withCredentials([
          usernamePassword
            (credentialsId: 'github', 
             usernameVariable: 'USERNAME', 
             passwordVariable: 'GIT_TOKEN'
            )
          ])

          {
            sh '''#!/busybox/sh
            /kaniko/executor \\
            --git branch=main \\
            --context=git://$USERNAME:$GIT_TOKEN@github.com/changukko/eshop-MSA.git \\
            --context-sub-path=eshop-currencyservice \\
            --destination=423149956628.dkr.ecr.us-east-1.amazonaws.com/eshop-currencyservice:latest
            '''
          }
        }
      }
    }
  }  
}